baseURL = "http://www.quartercreekyachtclub.com/"
languageCode = "en-us"
title = "Quarter Creek Yacht Club"
theme = "xmin"

# disqusShortname = "bogus"
# googleAnalytics = "bogus"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "\\.rst$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[params]
    description = "A website built with Hugo and the xmin theme."
    footer = "&copy; [Eric Gustafson](http://www.elfwerks.org/ericg) 2017 | Facebook | Twitter | other Social Media"

## ########################################
## Menus

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 100

[[menu.main]]
    name = "Past Voyages"
    url = "/voyages"
    weight = 200

[[menu.main]]
    name = "Past Excursions"
    url = "/excursions"
    weight = 300

[[menu.main]]
    name = "Future Adventures"
    url = "/future"
    weight = 400

[[menu.main]]
    name = "Members"
    url = "/members"
    weight = 500

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 800

# [[menu.main]]
#     name = "Credits"
#     url = "/credits/"
#     weight = 900

[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"
